service: default
api_version: 2
runtime: python27
threadsafe: yes

handlers:

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /(.*).(html|js|json|css)
  static_files: \1.\2
  upload: (.*)\.(html|js|json|css)
  secure: always

- url: /
  static_files: index.html
  upload: index\.html
  http_headers:
    Link: '</elements/elements.html>; rel=preload; as=document, </styles/main.css>; rel=preload; as=style'
    # Access-Control-Allow-Origin: "*"
  secure: always

skip_files:
- ^(.*/)?app\.yaml
